export const actionTypes = {
  REGISTER_USER: "REGISTER_USER",
  SIGN_IN: "SIGN_IN",
  ADMIN_SIGN_IN: "ADMIN_SIGN_IN",
  LOG_IN_ERROR: "LOG_IN_ERROR",
  LOG_OUT: "LOG_OUT",
  LOG_OUT_ALL: "LOG_OUT_ALL",
  FETCH_USER_EXPENSES: "FETCH_USER_EXPENSES",
  FETCH_ALL_EXPENSES: "FETCH_ALL_EXPENSES",
  // FETCH_SINGLE_EXPENSE: "FETCH_SINGLE_EXPENSE",
  ADD_EXPENSE: "ADD_EXPENSE",
  EDIT_EXPENSE: "EDIT_EXPENSE",
  DELETE_EXPENSE: "DELETE_EXPENSE",
  EXPENSES_ERROR: "EXPENSES_ERROR"
};
